#!/bin/bash
#
# Source this file from .bashrc
#

# Bash won't get SIGWINCH if another process is in the foreground.
# Enable checkwinsize so that bash will check the terminal size when
# it regains control.
# http://cnswww.cns.cwru.edu/~chet/bash/FAQ (E11)
shopt -s checkwinsize

# Enable history appending instead of overwriting.
shopt -s histappend

# Enable colors
if [ "$TERM" != dumb -o "$EMACS" = "t" -o -n "$INSIDE_EMACS" ]; then
	[[ $(type -t ls) == "alias" ]] && unalias ls
	[[ $(type -t ls) == "alias" ]] && unalias dir
	[[ $(type -t ls) == "alias" ]] && unalias grep
	[[ $(type -t ls) == "alias" ]] && unalias dmesg
	alias ls='ls $LS_OPTIONS'
	alias dir='ls $LS_OPTIONS --format=vertical'
	alias grep="grep --color=auto"
	alias dmesg='dmesg --color'

	# Set a nice PS1
	PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \W \$\[\033[00m\] '

	# Other PS1's
	#PS1='\[\033[01;35m\]\$\[\033[00m\] '
	#PS1='[\u@\h \W]\$ '
	#PS1='\[\033[35;01m\][\u@\h \W]\$\[\033[0m\] '
	#PS1='\[\e[0;32m\]\u\[\e[m\] \[\e[1;34m\]\w\[\e[m\] \[\e[1;32m\]\$\[\e[m\] \[\e[1;37m\]'
	#PS1="\[\033[01;32m\]\u@\h\[\033[01;34m\] \w \$([[ \$? != 0 ]] && echo \"\[\033[01;31m\]:(\[\033[01;34m\] \")\n\[\033[00;01m\]\$\[\033[00m\] "
	# (A) Cygwin-like prompt
	#PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$ '
	# (B) Cygwin-like prompt (no preceding \n)
	#PS1='\[\e]0;\w\a\]\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$ '
	# (C) One line Cygwin-like prompt
	#PS1='\[\e]0;\w\a\]\[\e[32m\]\u@\h \[\e[33m\]\w \$ \[\e[0m\]'
fi

# Aliases
alias ll='ls -l'
alias la='ls -la'
alias xyzzy='cd ~-/'
alias clip='xclip -selection c'
function qr { qrencode -o - "$@" | display; }
alias sk='slacklock'

# Detach-sign a bunch of stuff
signoff() {
	for f in "$@" ; do
		gpg --detach-sign "$f"
	done
}

# Allow local overrides
if [ -d "$HOME/.alias.d" ] ; then
    for file in "$HOME/.alias.d/"* ; do
        [ -r "$file" ] && . "$file"
    done
fi

:

# vim: ft=sh :
