#!/bin/bash
#
# boostrap
#
# Simlink and copy stuff.  This script attempts to do 80% of the work
# for you.
#

DOTFILES="$HOME/dotfiles"
DIFFTOOL="${DIFFTOOL:-vimdiff}"
cd "$HOME"

link() {
    local src="$1"
    local dst="$2"

    # If the file exists but is not a symlink, back it up
    if [[ -e "$dst" && ! -L "$dst" ]] ; then
        # Only backup files that differ
        # This check always succeeds on directories
        # (i.e. directories are always considered unique)
        if ! cmp -s "$src" "$dst" ; then
            echo "$dst: backing up to $dst.dotfilesbak"
            mv "$dst" "$dst.dotfilesbak"
        else
            rm "$dst"
        fi
    fi

    # Symlink it
    echo "$dst: linking from $src"
    ln -nsf "$src" "$dst"
}

copy() {
    local src="$1"
    local dst="$2"
    local ans=

    # If file exists, ask if we want to merge changes
    if [ -e "$dst" ] ; then
        if ! cmp -s "$src" "$dst" ; then
            echo -ne "$dst: differs from '$src'.  Merge changes? [Y/n]: "
            read ans
            if [[ "$ans" != "n" && "$ans" != "N" ]] ; then
                "$DIFFTOOL" "$dst" "$src"
            fi
        else
            echo "$dst: No changes"
        fi
    else
        echo "$dst: copying from $src"
        cp -p "$src" "$dst"
    fi
}

# Simple config files
link "dotfiles/alias" ".alias"
link "dotfiles/env" ".env"
link "dotfiles/emacs" ".emacs"
link "dotfiles/Xresources" ".Xresources"
copy "dotfiles/xautorun" ".xautorun"

# Vim
link "dotfiles/vimrc" ".vimrc"
link "dotfiles/vim" ".vim"

# bin
[ -d "bin" ] || mkdir "bin"
link "../dotfiles/bin/cht" "bin/cht"
link "../dotfiles/bin/chte" "bin/chte"
link "../dotfiles/bin/ec" "bin/ec"
link "../dotfiles/bin/fix-permissions" "bin/fix-permissions"
link "../dotfiles/bin/slacklock" "bin/slacklock"
link "../dotfiles/bin/sshfs-helper" "bin/sshfs-helper"

# Git
copy "dotfiles/gitconfig" ".gitconfig"

# Openbox
mkdir -p ".config/openbox"
copy "dotfiles/openbox/autostart" ".config/openbox/autostart"
copy "dotfiles/openbox/environment" ".config/openbox/environment"
copy "dotfiles/openbox/menu.xml" ".config/openbox/menu.xml"
copy "dotfiles/openbox/rc.xml" ".config/openbox/rc.xml"
mkdir -p ".config/tint2"
copy "dotfiles/tint2/vertical-neutral-icons.tint2rc" ".config/tint2/vertical-neutral-icons.tint2rc"
copy "dotfiles/tint2/horizontal-custom.tint2rc" ".config/tint2/horizontal-custom.tint2rc"
#copy ".config/tint2/vertical-neutral-icons.tint2rc" ".config/tint2/tint2rc"
