#!/bin/sh
#
# ~/.xautorun
#

# gpg-agent
# <https://wiki.archlinux.org/index.php/GnuPG#SSH_agent>
if which gpg-connect-agent &> /dev/null; then
	## Start the gpg-agent if not already running
	## Normally, this is handled by systemd
	#if ! pgrep -x -u "${USER}" gpg-agent >/dev/null 2>&1; then
	#	gpg-connect-agent /bye >/dev/null 2>&1
	#fi
	# Set SSH to use gpg-agent
	unset SSH_AGENT_PID
	if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
		export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"
	fi
	# Set GPG TTY
	export GPG_TTY=$(tty)
	# Refresh gpg-agent tty in case user switches into an X session
	gpg-connect-agent updatestartuptty /bye >/dev/null
fi

# Load Xresources
xrdb -merge "$HOME/.Xresources"

# Mouse acceleration
xset m 4/1 4

# Keyboard
xset r rate 250 40
#setxkbmap -option compose:caps
#setxkbmap -option 'ctrl:swapcaps,compose:lctrl'
#setxkbmap -option 'ctrl:nocaps'
setxkbmap -option 'caps:escape'
numlockx on

# Set the Desktop Environment
#export DE=xfce

#
# Startup programs
# These will likely be different on each machine
#

# Core
#dbus-launch --sh-syntax --exit-with-session &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
#/usr/libexec/polkit-gnome-authentication-agent-1 &
#/usr/bin/gnome-keyring-daemon --start --components=secrets &
start-pulseaudio-x11 &
#/home/kyle/bin/compton-start &

# GTK settings and screensaver
#xsettingsd &
/usr/lib/mate-settings-daemon/mate-settings-daemon &
xset dpms 900 900 900 &
xset s off &
xautolock -time 15 -locker 'i3exit lock' &
#light-locker &
#mate-power-manager &
mate-screensaver &
#xscreensaver -no-splash &

# MATE applications
#/usr/lib/mate-user-share/mate-user-share &
#mate-volume-control-applet &

# Tray/background apps
#nm-applet &
#volumeicon &
pasystray &
#system-config-printer-applet &
#conky &
#dropboxd &
#/home/kyle/bin/xpenguins-start &
