#!/bin/sh

if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

export EDITOR=/usr/bin/vim

# Start the GnuPG agent and enable OpenSSH agent emulation
gnupginf="${HOME}/.gpg-agent-info"

if pgrep -x -u "${USER}" gpg-agent >/dev/null 2>&1; then
    eval `cat $gnupginf`
    eval `cut -d= -f1 $gnupginf | xargs echo export`
    export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"
else
    eval `gpg-agent -s --enable-ssh-support --daemon --write-env-file "$gnupginf"`
fi

# Set monitor settings
configure-monitors

# Load Xresources
xrdb "$HOME/.Xresources"

# Compose key
setxkbmap -option compose:caps
numlockx on
