#!/bin/sh
#
# autostart
#
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#

# If you want to use GNOME config tools...
#
#if test -x /usr/libexec/gnome-settings-daemon >/dev/null; then
#  /usr/libexec/gnome-settings-daemon &
#elif which gnome-settings-daemon >/dev/null; then
#  gnome-settings-daemon &
#fi

# If you want to use XFCE config tools...
#
#xfce-mcs-manager &

#xsetroot -solid \#303030 &
#xsetroot -solid \#808080 &
#xsetroot -solid \#505075 &

wmsetbg -p '(solid, "#303030")' &
#xcompmgr &

tint2 &
[ -x "$HOME/.xautorun" ] && "$HOME/.xautorun" &
